plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    mavenCentral()
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "BlameJared"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

loom {
    runs {
        client {
            client()
            name = "Fabric Client"
            vmArg "-Djava.net.preferIPv4Stack=true"
            programArgs "--username", "UnhappyWithoutU", "--uuid", "407db9d7-7c5f-4fd4-82b2-a800bdff0b39", "--width", "1920", "--height", "1080"
        }

        server {
            server()
            name = "Fabric Server"
            vmArg "-Djava.net.preferIPv4Stack=true"
            runDir "runs/server-dev"
            programArgs "--port", "25566", "--nogui"
        }

        datagen {
            client()
            name = "Fabric Datagen"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"
            vmArg "-Dfabric-api.datagen.output-dir=${file('src/generated/resources').absolutePath}"
            vmArg "-Dfabric-api.datagen.strict-validation"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    include implementation("teamreborn:energy:${reborn_energy_version}")
    implementation "com.terraformersmc:modmenu:${modmenu_version}"
    localRuntime "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    localRuntime "maven.modrinth:3eMENr4V:${techreborn_modrinth_version_id}"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
}

tasks.withType(ProcessResources).configureEach {
    inputs.property "version", project.version
    inputs.property "mod_id", mod_id
    inputs.property "mod_name", mod_name
    inputs.property "mod_license", mod_license
    inputs.property "minecraft_version", minecraft_version
    inputs.property "loader_version", loader_version
    inputs.property "fabric_api_version", fabric_api_version
    inputs.property "reborn_energy_version", reborn_energy_version

    filesMatching("fabric.mod.json") {
        expand(
                version: project.version,
                mod_id: mod_id,
                mod_name: mod_name,
                mod_license: mod_license,
                minecraft_version: minecraft_version,
                loader_version: loader_version,
                fabric_api_version: fabric_api_version,
                reborn_energy_version: reborn_energy_version
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = mod_id
            from components.java
        }
    }
    repositories {
        maven {
            url = uri("${project.projectDir}/repo")
        }
    }
}
