org.gradle.jvmargs=-Xmx16G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16.1
fabric_api_version=0.155.2+26.1.2

## Mod Properties

mod_id=quarry
mod_name=Quarry
mod_license=MIT
mod_version=2.3.0
mod_group_id=de.unhappycodings.quarry

reborn_energy_version=5.0.0
techreborn_modrinth_version_id=odOcmoOg
modmenu_version=18.0.0-alpha.8
jei_version=29.21.0.66
