modLoader = "javafml"
loaderVersion = "[41,)"
license = "All Rights Reserved"
[[mods]]
modId = "quarry"
version = "1.6.4r"
displayName = "Quarry"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/quarry"
logoFile = "quarry-logo.png"
authors = "UnhappyWithoutU"
description = ''''''

[[dependencies.quarry]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quarry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
