modLoader = "javafml"
loaderVersion = "[41,)"
license = "All Rights Reserved"
[[mods]]
modId = "vanillaquarry"
version = "1.0r"
displayName = "VanillaQuarry"
authors = "UnhappyWithoutU"
description = ''''''

[[dependencies.vanillaquarry]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillaquarry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
