modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"
[[mods]]
modId = "quarry"
version = "1.2r"
displayName = "Quarry"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/quarry"
logoFile = "quarry-logo.png"
authors = "UnhappyWithoutU"
description = ''''''

[[dependencies.quarry]]
modId = "forge"
mandatory = true
versionRange = "[40.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quarry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
