modLoader = "javafml"
loaderVersion = "[41,)"
license = "All Rights Reserved"
[[mods]]
modId = "quarry"
version = "1.0r"
displayName = "Quarry"
authors = "UnhappyWithoutU"
description = ''''''

[[dependencies.quarry]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quarry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
