modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"
[[mods]]
modId = "vanillaquarry"
version = "1.0r"
displayName = "VanillaQuarry"
authors = "UnhappyWithoutU"
description = ''''''

[[dependencies.vanillaquarry]]
modId = "forge"
mandatory = true
versionRange = "[40.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillaquarry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
